version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: postgresql://postgres:123@dev-db:5432/nest?schema=public
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8080:3000'
    networks:
      - freecodecamp

  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp:
